global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: json-exporter
    static_configs:
      - targets: ["exporter:9110"]

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node"
    static_configs:
      - targets: ["nodeexporter:9100"]